---
- name: Create
  hosts: localhost
  connection: local
  gather_facts: false
  no_log: "{{ molecule_no_log }}"
  tasks:
    - name: Create molecule instance(s)
      vagrant:
        instances: "{{ molecule_yml.platforms }}"
        provider: "{{ molecule_yml.driver.provider.name | default('virtualbox') }}"
        parallel: "{{ molecule_yml.driver.provider.parallel | default(True) }}"
        state: up
      register: server
      no_log: false

    # Mandatory configuration for Molecule to function.
    - when: server.changed | bool
      block:
        - name: Populate instance config dict
          set_fact:
            instance_conf_dict: {
              'instance': "{{ item.Host }}",
              'address': "{{ item.HostName }}",
              'user': "{{ item.User }}",
              'port': "{{ item.Port }}",
              'identity_file': "{{ item.IdentityFile }}", }
          with_items: "{{ server.results }}"
          register: instance_config_dict

        - name: Convert instance config dict to a list
          set_fact:
            instance_conf: "{{ instance_config_dict.results | map(attribute='ansible_facts.instance_conf_dict') | list }}"

        - name: Dump instance config
          copy:
            content: "{{ instance_conf | to_json | from_json | molecule_to_yaml | molecule_header }}"
            dest: "{{ molecule_instance_config }}"
